import { Rubik } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Providers from "./components/Providers";
import "react-datepicker/dist/react-datepicker.css";
import { Toaster } from "sonner";

const mons = Rubik({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mons.className}>
        <div>
          <Toaster position="top-center" richColors duration={3000} />
        </div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
